name: Run Checks

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
      
jobs:
  run-checks:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Install System Dependencies
        run: |
          apt-get update
          apt-get install -y curl
      
      - name: Set Up Python ${{ matrix.python-version }}
        uses: useblacksmith/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install UV
        run: |
          curl -LsSf https://astral.sh/uv/0.6.3/install.sh | sh
          echo "/root/.local/bin" >> $GITHUB_PATH
      
      - name: Check Lock File Sync
        run: uv lock --locked
      
      - name: Install Python Dependencies
        run: uv sync --frozen --no-install-project
      
      - name: Lint With Ruff
        run: uv run ruff check
      
      - name: Test With PyTest
        run: pytest --cov=./ --cov-report=xml
      
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}