name: Continuous Integration

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main

jobs:
  checks:
    uses: ./.github/workflows/checks.yml
    secrets: inherit

  build-and-push-image:
    needs: checks
    uses: ./.github/workflows/build_and_push_image.yml
    secrets: inherit
