name: CI

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: python:3.12-slim
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Install System Dependencies
        run: |
          apt-get update
          apt-get install -y curl
      
      - name: Install UV
        run: |
          curl -LsSf https://astral.sh/uv/0.6.3/install.sh | sh
          echo "/root/.local/bin" >> $GITHUB_PATH
      
      - name: Check Lock File Sync
        run: uv lock --locked
      
      - name: Install Python Dependencies
        run: uv sync --frozen --no-install-project
      
      - name: Lint With Ruff
        run: uv run ruff check
      
      - name: Test With PyTest
        run: pytest --cov=./ --cov-report=xml