name: Continuous Integration

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main

jobs:
  checks:
    strategy:
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
      uses: ./.github/workflows/checks.yml
      with:
        python-version: ${{ matrix.python-version }}
      secrets: inherit

  build-and-push-image:
    needs: checks
    uses: ./.github/workflows/build_and_push_image.yml
    secrets: inherit
